# docker-compose.yml
version: '3.8'

services:
  jyo-app:
    build: .
    container_name: jyo-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jyo.rule=Host(`jyo.pavan.today`)"
      - "traefik.http.routers.jyo.entrypoints=web"
      - "traefik.http.services.jyo.loadbalancer.server.port=3000"
    networks:
      - web
    restart: always

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    external: true
